const list = [
  'autolla ajaminen',
  'auton korjaaminen',
  'bloggaaminen',
  'crossfit',
  'DIY-projektit',
  'drone-lennättäminen',
  'e-sporttailu',
  'elokuvien katselu',
  'eläinten hoitaminen',
  'festareilla käyminen',
  'graafinen suunnittelu',
  'graffitien tekeminen',
  'geokätköily',
  'grillaaminen',
  'hiihtäminen',
  'hiustenhoito',
  'hierojalla käyminen',
  'ihmisten hoitaminen',
  'illanistujaiset',
  'itsepuolustuslajit',
  'jooga',
  'juhlien järjestäminen',
  'kalastus',
  'keramiikka',
  'keskusteleminen',
  'kiipeily',
  'kirjanpito',
  'kirjoittaminen',
  'kirjojen kuuntelu',
  'kirpputorikiertely',
  'koira-agility',
  'kokkaaminen',
  'konmaritus',
  'konsolipelaaminen',
  'koodaaminen',
  'kuntoilu',
  'kuntosalitreeni',
  'kuorolaulu',
  'kynsien laittaminen',
  'käsityöt',
  'laitteiden korjaus',
  'laskeminen',
  'lastenhoito',
  'laulaminen',
  'legojen rakentelu',
  'leipominen',
  'lemmikin hoitaminen',
  'lenkkeily',
  'lukeminen',
  'matkustaminen',
  'meikkaaminen',
  'metsäretket',
  'mietiskely',
  'moottoripyörän rassaaminen',
  'muotisuunnittelu',
  'musiikin kuuntelu',
  'myyntityö',
  'mökkeily',
  'neulominen',
  'nuotiolla istuskelu',
  'näytteleminen',
  'ohjelmointi',
  'ompeleminen',
  'palapelien rakentelu',
  'parkour',
  'patikointi',
  'pelaaminen',
  'picnicit',
  'piirtäminen',
  'pilkkiminen',
  'podcastaaminen',
  'puheen pitäminen',
  'puutarhanhoito',
  'puutyöt',
  'pyöräily',
  'rakentaminen',
  'ratsastaminen',
  'remontointi',
  'retkeily',
  'rukoilu',
  'runojen kirjoittaminen',
  'sanaristikoiden täyttäminen',
  'sarjojen bingettäminen',
  'saunominen',
  'shoppailu',
  'sijoittaminen',
  'sisustaminen',
  'soittiminen soittaminen',
  'somesisältöjen tekeminen',
  'stand-up -esitysten katseleminen',
  'sukellus',
  'tanssiminen',
  'tiktokkaaminen',
  'tubettaminen',
  'uiminen',
  'valmentaminen',
  'valokuvaus',
  'vapaaehtoistyö',
  'vapaapalokunta',
  'veneily',
  'videoiden kuvaaminen',
  'videoiden editoiminen',
  'voimanosto',
  'värityskirjojen värittäminen',
  'yleisurheilu',
  'yrittäminen'
];

export default list;
