const list = [
  'autolla ajaminen',
  'auton korjaaminen',
  'bloggaaminen',
  'crossfit',
  'DIY-projektit',
  'drone-lennättäminen',
  'e-sporttailu',
  'elokuvien katselu',
  'eläinten hoitaminen',
  'festareilla käyminen',
  'geokätköily',
  'grillaaminen',
  'hiihtäminen',
  'ihmisten hoitaminen',
  'illanistujaiset',
  'jooga',
  'juhlien järjestäminen',
  'kalastus',
  'keramiikka',
  'keskusteleminen',
  'kiipeily',
  'kirjanpito',
  'kirjoittaminen',
  'kirjojen kuuntelu',
  'kirpputorikiertely',
  'kokkaaminen',
  'konmaritus',
  'konsolipelaaminen',
  'koodaaminen',
  'kuntoilu',
  'kuntosalitreeni',
  'kuorolaulu',
  'käsityöt',
  'laitteiden korjaus',
  'laskeminen',
  'lastenhoito',
  'legojen rakentelu',
  'leipominen',
  'lemmikin hoitaminen',
  'lenkkeily',
  'lukeminen',
  'matkustaminen',
  'meikkaaminen',
  'metsäretket',
  'mietiskely',
  'moottoripyörän rassaaminen',
  'musiikin kuuntelu',
  'mökkeily',
  'neulominen',
  'näytteleminen',
  'ohjelmointi',
  'ompeleminen',
  'palapelien rakentelu',
  'pelaaminen',
  'piirtäminen',
  'pilkkiminen',
  'puheen pitäminen',
  'puutarhanhoito',
  'puutyöt',
  'pyöräily',
  'rakentaminen',
  'ratsastaminen',
  'remontointi',
  'retkeily',
  'rukoilu',
  'runojen kirjoittaminen',
  'sanaristikoiden täyttäminen',
  'sarjojen bingettäminen',
  'saunominen',
  'shoppailu',
  'sijoittaminen',
  'sisustaminen',
  'soittiminen soittaminen',
  'stand-up -esitysten katseleminen',
  'sukellus',
  'tanssiminen',
  'uiminen',
  'valmentaminen',
  'valokuvaus',
  'vapaaehtoistyö',
  'vapaapalokunta'];

export default list;
